swagger: "2.0"
info:
  title: VeriForge Ops
  description: VeriForge Ops LLMOps Platform
  version: "1.0"
host: "veriforgeops.endpoints.cog01k24f1ea555zdv7ynzthxanz5.cloud.goog"
x-google-endpoints:
  - name: "veriforgeops.endpoints.cog01k24f1ea555zdv7ynzthxanz5.cloud.goog"
    target: "34.160.87.71"
paths: {}
