const Alert = require('../models/Alert');

// Canonical agents:
// demo:          agent-001 Concierge Agent, agent-002 Public Research Agent,
//                agent-003 Insurance Underwriting Agent, agent-005 Shipment Insight Agent,
//                agent-009 Workforce Planning and Recruitment
// arcadia-health: agent-101 Insurance Underwriting Agent, agent-102 Workforce Planning and Recruitment
// zenith-capital: agent-201 Trade Compliance Monitor, agent-202 Market Surveillance Agent,
//                 agent-203 Capital Adequacy Validator, agent-204 AML Detection Engine,
//                 agent-205 Regulatory Reporting Agent, agent-206 Risk Exposure Calculator

module.exports = async function seedAlerts() {
  await Alert.deleteMany({});
  const now = Date.now();
  await Alert.insertMany([

    // ── demo — active alerts ──────────────────────────────────────────────────
    { alert_id: 'DM-C-001', tenant_id: 'demo', agentName: 'Public Research Agent',             model_id: 'anthropic.claude-3-5-sonnet-20241022-v2:0', severity: 'P1', timestamp: new Date(now - 6*60000),   message: 'Prompt injection detected — adversarial payload attempting to override research scope constraints and extract internal configuration data', resolved: false },
    { alert_id: 'DM-W-001', tenant_id: 'demo', agentName: 'Concierge Agent',                   model_id: 'anthropic.claude-3-5-haiku-20241022-v1:0',  severity: 'P2', timestamp: new Date(now - 18*60000),  message: 'Token usage at 84% of daily limit — high inbound request volume forecast to breach quota within 3 hours', resolved: false },
    { alert_id: 'DM-W-002', tenant_id: 'demo', agentName: 'Shipment Insight Agent',            model_id: 'amazon.nova-pro-v1:0',                      severity: 'P2', timestamp: new Date(now - 33*60000),  message: 'ReAct loop counter at 2/3 threshold — agent nearing automatic termination limit on shipment ETA recalculation chain', resolved: false },

    // ── demo — historical alerts ──────────────────────────────────────────────
    { alert_id: 'DM-H-001', tenant_id: 'demo', agentName: 'Concierge Agent',                   model_id: 'anthropic.claude-3-5-haiku-20241022-v1:0',  severity: 'CRITICAL', timestamp: new Date('2026-06-08T10:12:00.000Z'), message: 'Bedrock endpoint connectivity lost for 38s — 142 concierge sessions dropped during morning peak', request_id: 'req_DM_INC001', resolved: true, resolved_at: new Date('2026-06-08T11:00:00.000Z') },
    { alert_id: 'DM-H-002', tenant_id: 'demo', agentName: 'Shipment Insight Agent',            model_id: 'amazon.nova-pro-v1:0',                      severity: 'CRITICAL', timestamp: new Date('2026-06-15T14:22:00.000Z'), message: 'ReAct loop circuit breaker tripped — infinite ETA recalculation loop on 7 stale shipment records; agent restarted', request_id: 'req_DM_INC002', resolved: true, resolved_at: new Date('2026-06-15T15:00:00.000Z') },
    { alert_id: 'DM-H-003', tenant_id: 'demo', agentName: 'Insurance Underwriting Agent',      model_id: 'anthropic.claude-3-opus-20240229-v1:0',     severity: 'CRITICAL', timestamp: new Date('2026-06-22T09:30:00.000Z'), message: 'Context window overflow — underwriting corpus retrieval exceeded 200K token limit on complex multi-policy batch', request_id: 'req_DM_INC003', resolved: true, resolved_at: new Date('2026-06-22T10:15:00.000Z') },
    { alert_id: 'DM-H-004', tenant_id: 'demo', agentName: 'Public Research Agent',             model_id: 'anthropic.claude-3-5-sonnet-20241022-v2:0', severity: 'ERROR',    timestamp: new Date('2026-06-30T13:45:00.000Z'), message: 'Data exfiltration gate triggered — research output contained internal API key pattern; output blocked and incident logged', request_id: 'req_DM_c004', resolved: false },
    { alert_id: 'DM-H-005', tenant_id: 'demo', agentName: 'Workforce Planning and Recruitment',model_id: 'gpt-5.5',                                  severity: 'WARNING',  timestamp: new Date('2026-07-05T11:20:00.000Z'), message: 'Palantir AIP exec_0000019f-5f99-e046 (trace cf45a9c07516ae76): Semantic drift score 0.38 — OntologySqlTool query on CandidateProfiles diverging from approved staffing baseline; recalibration recommended [source: Palantir Foundry Audit Log → staging datastore]', request_id: 'req_DM_w001', resolved: false },
    { alert_id: 'DM-H-006', tenant_id: 'demo', agentName: 'Concierge Agent',                   model_id: 'anthropic.claude-3-5-haiku-20241022-v1:0',  severity: 'WARNING',  timestamp: new Date('2026-07-10T16:08:00.000Z'), message: 'Response latency p95 at 3.8s — above 3.0s SLA threshold for 8 consecutive requests during afternoon peak', request_id: 'req_DM_w002', resolved: false },

    // ── arcadia-health — active alerts ────────────────────────────────────────
    { alert_id: 'AHA-C-001', tenant_id: 'arcadia-health', agentName: 'Insurance Underwriting Agent', model_id: 'anthropic.claude-sonnet-4-5-20250929-v1:0', severity: 'P1', timestamp: new Date(now - 8*60000),   message: 'Hallucination score 0.26 — above 0.20 threshold on risk assessment output; 3 policy applications flagged for manual review', resolved: false },
    { alert_id: 'AHA-C-002', tenant_id: 'arcadia-health', agentName: 'Insurance Underwriting Agent', model_id: 'anthropic.claude-sonnet-4-5-20250929-v1:0', severity: 'P1', timestamp: new Date(now - 41*60000),  message: 'Bedrock endpoint HTTP 503 — retry budget exhausted (3/3); underwriting pipeline stalled for high-priority applications', resolved: false },
    { alert_id: 'AHA-W-001', tenant_id: 'arcadia-health', agentName: 'Insurance Underwriting Agent', model_id: 'anthropic.claude-sonnet-4-5-20250929-v1:0', severity: 'P2', timestamp: new Date(now - 14*60000),  message: 'Token usage at 87% of daily limit (435K/500K) — underwriting queue may throttle within 2 hours', resolved: false },
    { alert_id: 'AHA-W-002', tenant_id: 'arcadia-health', agentName: 'Workforce Planning and Recruitment', model_id: 'anthropic.claude-sonnet-4-5-20250929-v1:0', severity: 'P2', timestamp: new Date(now - 55*60000),  message: 'Embedding drift 0.23 above 0.20 threshold — workforce demand forecast model recalibration advised', resolved: false },
    { alert_id: 'AHA-W-003', tenant_id: 'arcadia-health', agentName: 'Workforce Planning and Recruitment', model_id: 'anthropic.claude-sonnet-4-5-20250929-v1:0', severity: 'P3', timestamp: new Date(now - 134*60000), message: 'p95 latency 4.1s — SLA threshold 3.0s breached for 12 consecutive recruitment pipeline requests', resolved: false },

    // ── arcadia-health — historical alerts ───────────────────────────────────
    { alert_id: 'AHA-H-001', tenant_id: 'arcadia-health', agentName: 'Insurance Underwriting Agent', model_id: 'anthropic.claude-sonnet-4-5-20250929-v1:0', severity: 'CRITICAL', timestamp: new Date('2026-06-10T10:14:00.000Z'), message: 'API Timeout — Bedrock endpoint unreachable for 47s during morning underwriting peak (18 applications failed)', request_id: 'req_AHA_INC001', resolved: true, resolved_at: new Date('2026-06-10T11:00:00.000Z') },
    { alert_id: 'AHA-H-002', tenant_id: 'arcadia-health', agentName: 'Insurance Underwriting Agent', model_id: 'anthropic.claude-sonnet-4-5-20250929-v1:0', severity: 'CRITICAL', timestamp: new Date('2026-06-18T14:32:00.000Z'), message: 'Bedrock rate limit exhausted — 429 responses for 76 consecutive requests during peak underwriting window', request_id: 'req_AHA_INC002', resolved: true, resolved_at: new Date('2026-06-18T15:00:00.000Z') },
    { alert_id: 'AHA-H-003', tenant_id: 'arcadia-health', agentName: 'Workforce Planning and Recruitment', model_id: 'anthropic.claude-sonnet-4-5-20250929-v1:0', severity: 'CRITICAL', timestamp: new Date('2026-06-24T08:30:00.000Z'), message: 'Context window overflow — recruitment corpus retrieval exceeded 200K token limit processing 8 concurrent role analyses', request_id: 'req_AHA_INC003', resolved: true, resolved_at: new Date('2026-06-24T09:15:00.000Z') },
    { alert_id: 'AHA-H-004', tenant_id: 'arcadia-health', agentName: 'Insurance Underwriting Agent', model_id: 'anthropic.claude-sonnet-4-5-20250929-v1:0', severity: 'CRITICAL', timestamp: new Date('2026-07-01T14:32:00.000Z'), message: 'Token quota exceeded — daily limit of 500K tokens reached at 14:32 with 6 hours remaining', request_id: 'req_AHA_c004', resolved: false },
    { alert_id: 'AHA-H-005', tenant_id: 'arcadia-health', agentName: 'Insurance Underwriting Agent', model_id: 'anthropic.claude-sonnet-4-5-20250929-v1:0', severity: 'ERROR',    timestamp: new Date('2026-07-06T09:18:00.000Z'), message: 'Underwriting pipeline stalled — Bedrock timeout after 3 retries for high-risk application batch #AH-7741', request_id: 'req_AHA_c005', resolved: false },
    { alert_id: 'AHA-H-006', tenant_id: 'arcadia-health', agentName: 'Insurance Underwriting Agent', model_id: 'anthropic.claude-sonnet-4-5-20250929-v1:0', severity: 'WARNING',  timestamp: new Date('2026-07-10T15:02:00.000Z'), message: 'Token usage at 87% of daily budget — 65,000 tokens remaining with peak afternoon underwriting hours ahead', request_id: 'req_AHA_w001', resolved: false },
    { alert_id: 'AHA-H-007', tenant_id: 'arcadia-health', agentName: 'Workforce Planning and Recruitment', model_id: 'anthropic.claude-sonnet-4-5-20250929-v1:0', severity: 'WARNING',  timestamp: new Date('2026-07-11T13:30:00.000Z'), message: 'Response latency degraded — p95 at 4.1s (SLA threshold: 3.0s) for 12 consecutive recruitment pipeline requests', request_id: 'req_AHA_w002', resolved: false },
    { alert_id: 'AHA-H-008', tenant_id: 'arcadia-health', agentName: 'Workforce Planning and Recruitment', model_id: 'anthropic.claude-sonnet-4-5-20250929-v1:0', severity: 'WARNING',  timestamp: new Date('2026-07-12T11:45:00.000Z'), message: 'Embedding drift 0.23 — workforce demand baseline recalibration required; forecast accuracy declining', request_id: 'req_AHA_w003', resolved: false },

    // ── zenith-capital — active alerts ────────────────────────────────────────
    { alert_id: 'ZCA-C-001', tenant_id: 'zenith-capital', agentName: 'Capital Adequacy Validator',  model_id: 'anthropic.claude-3-opus-20240229-v1:0',     severity: 'P1', timestamp: new Date(now - 15*60000),  message: 'Basel III capital ratio breach — CET1 ratio 8.1% vs 8.5% regulatory minimum; stress scenario recompute required', resolved: false },
    { alert_id: 'ZCA-C-002', tenant_id: 'zenith-capital', agentName: 'Market Surveillance Agent',   model_id: 'anthropic.claude-3-5-sonnet-20241022-v2:0', severity: 'P1', timestamp: new Date(now - 30*60000),  message: 'MNPI detection triggered — potential insider information pattern across 7 equity positions; trading halt signalled', resolved: false },
    { alert_id: 'ZCA-W-001', tenant_id: 'zenith-capital', agentName: 'Trade Compliance Monitor',    model_id: 'anthropic.claude-sonnet-4-5',               severity: 'P2', timestamp: new Date(now - 42*60000),  message: 'MiFID II trade reporting latency 6.2s — T+1 SLA at risk for 14 equity positions', resolved: false },
    { alert_id: 'ZCA-W-002', tenant_id: 'zenith-capital', agentName: 'AML Detection Engine',        model_id: 'amazon.nova-pro-v1:0',                      severity: 'P2', timestamp: new Date(now - 61*60000),  message: 'AML false-positive rate spike 12% — APAC clearing queue backlog of 38 flagged transactions', resolved: false },
    { alert_id: 'ZCA-W-003', tenant_id: 'zenith-capital', agentName: 'Regulatory Reporting Agent',  model_id: 'anthropic.claude-3-5-haiku-20241022-v1:0',  severity: 'P3', timestamp: new Date(now - 90*60000),  message: 'EMIR report generation latency 8.8s — EU submission deadline at T+1 business day', resolved: false },
    { alert_id: 'ZCA-W-004', tenant_id: 'zenith-capital', agentName: 'Risk Exposure Calculator',    model_id: 'anthropic.claude-3-5-sonnet-20241022-v2:0', severity: 'P3', timestamp: new Date(now - 120*60000), message: 'VaR model divergence 18% above baseline — overnight recalibration recommended', resolved: false },

    // ── zenith-capital — historical alerts ───────────────────────────────────
    { alert_id: 'ZCA-H-001', tenant_id: 'zenith-capital', agentName: 'Trade Compliance Monitor',   model_id: 'anthropic.claude-sonnet-4-5',               severity: 'CRITICAL', timestamp: new Date('2026-06-01T09:12:00.000Z'), message: 'MiFID II reporting blackout — Bedrock connectivity lost for 52s during pre-market window; 31 trade reports failed', request_id: 'req_ZCA_INC001', resolved: true, resolved_at: new Date('2026-06-01T10:00:00.000Z') },
    { alert_id: 'ZCA-H-002', tenant_id: 'zenith-capital', agentName: 'Capital Adequacy Validator', model_id: 'anthropic.claude-3-opus-20240229-v1:0',     severity: 'CRITICAL', timestamp: new Date('2026-06-20T14:18:00.000Z'), message: 'ICAAP stress model OOM — 9 concurrent scenario batches exhausted heap (RSS: 18.1 GB); Basel III recalculation queued', request_id: 'req_ZCA_INC002', resolved: true, resolved_at: new Date('2026-06-20T15:30:00.000Z') },
    { alert_id: 'ZCA-H-003', tenant_id: 'zenith-capital', agentName: 'AML Detection Engine',       model_id: 'amazon.nova-pro-v1:0',                      severity: 'WARNING',  timestamp: new Date('2026-07-02T11:45:00.000Z'), message: 'AML pattern corpus embedding drift 0.24 — above 0.20 threshold; model recalibration scheduled', request_id: 'req_ZCA_w001', resolved: false },

  ]);
};
